### ISSUE TITLE
Move bower dependencies to npm?

### ISSUE THREAD

**Issue by rbayliss** [LastCallMedia/Drupal-Scaffold#10]
We're currently only pulling in Foundation.  I can't think of a compelling reason to stick with Bower over NPM here, and it means one less dependency.

**Comment by jlandfried** [comment]
I'm not opposed to it. How would we access the assets from theme? Referencing assets from the theme that live in `{project_root}/node_modules` doesn't seem ideal, but maybe there's a clean way to work around that?

We've also used a couple of libraries that appear on bower's package registry, but not in the npm registry (minimalect, jquery-infinite-scroll). Any thoughts about how we'd work with those situations (or maybe going forward we'd just look for alternative libraries).

**Comment by rbayliss** [comment]
It's kind of the same problem we currently have with Bower assets.  In cases where we do have to reference bower assets from our custom code, we have the sassOptions thing (see the default gulpconfig).  That would look basically the same for node_modules.  

Regarding the things that aren't on the NPM registry, that's a good point, although it seems equally likely to happen in the opposite direction, especially in the future.  Are there more examples that just those two libraries?

**Comment by jlandfried** [comment]
Nope, those are the only two that I can think of. And fwiw, I don't really care for either of them, I just kind of would guess that the more front-endy packages would end up in bower's registry before npm's, but that's just based off of the stereotype in my head that bower is for front-endy than npm, no facts there. Either way, I'm pretty sure that we can almost always find an alternative in whatever system we go with.

**Comment by rbayliss** [comment]
Fixed in #30.  Bower's still around for now and will work if you have it configured, but the default configuration no longer uses it.
