### ISSUE TITLE
Installing with Docker

### ISSUE THREAD

**Issue by smerth** [LastCallMedia/Drupal-Scaffold#26]
Hello Everyone at LCM,

I think your template looks fantastic and ticks all the boxes for a "dream" build system for Drupal 8.  But I am having trouble getting things up and running.  This is the process I am following…   But in the end I cannot access anything on [http://localhost/8080](http://localhost:8080).   Can you see what I am missing?

---

These are the steps I have taken to try and get up and running with the scaffold.
---

```
composer create-project lastcall/drupal-scaffold PROJECTNAME
```
Move into the project root

```bash
cd PROJECTNAME
```

I don't have nvm installed so I updated my version of npm with:

```bash
npm install npm@latest -g
```

Install nodejs dependencies

```bash
npm install
```

Install bower and composer dependencies

```bash
gulp install
```

Edited the `composer.json`, `package.json`, and `bower.json` and rename the project as needed.

Renamed the scaffold theme to match my project (including JS and SCSS files).

Edited the project readme.md.

Initialize a new git repository and push work to it as normal

```bash
git init && git add . && git commit
```

Create a repo on github and push to origin...

Everything to this point is smooth.

With all the peices in place I think the next step is to get Drupal installed with a database.

 If I were using [drupal-composer/drupal-scaffold](https://github.com/drupal-composer/drupal-scaffold) and I would run: 

```bash
drupal site:install standard --langcode="en" \
--db-type="mysql" --db-host="127.0.0.1" \
--db-name="databasename" --db-user="root" \
--db-pass="root-user-password" --db-port="3306" \
--site-name="Site Name" \
--site-mail="site@mail.com" \
--account-name="admin" \
--account-mail="admin@mail.com" \
--account-pass="admin" \
--no-interaction
```

But I would like to use Docker and follow your repos build philosophy.  So I ran:

```bash
docker-compose -f docker-compose.yml -f docker-compose.debug.yml up
```

I thought this would create a Docker container and a database and install Drupal and give me access to it at: 

- Varnish: You can still access the site behind varnish as you would with only the default config at [http://localhost:8080](http://localhost:8080)
- Drupal: You can directly access the Drupal site, bypassing the reverse proxy at [http://localhost:8081](http://localhost:8081) 
- MySQL: You can make a direct connection from the command line using `mysql -h 127.0.0.1 --port 33306 -u drupal -pdrupal drupal`

However, when I go to [http://localhost:8080](http://localhost:8080) I get  a "You don't have permission to access / on this server."  with this kind of feedback from the console:

```bash
drupal_1   | 172.18.0.5 - - [03/Mar/2017:00:06:39 +0000] "GET / HTTP/1.1" 403 447 "-" "Mozilla/5.0 (Macintosh; Intel Mac O
S X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
drupal_1   | 172.18.0.5 - - [03/Mar/2017:00:18:42 +0000] "GET / HTTP/1.1" 403 447 "-" "Mozilla/5.0 (Macintosh; Intel Mac O
S X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
drupal_1   | [Fri Mar 03 00:18:42.082713 2017] [autoindex:error] [pid 16] [client 172.18.0.5:52858] AH01276: Cannot serve
directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index fo
rbidden by Options directive
```

Obvisously, I am missing a step...

BTW, I can access a database named drupal at: `mysql -h 127.0.0.1 --port 33306`  but there are no tables in it, So I guess Docker is not actually installing Drupal?  

I have worked with just about every aspect of this build environement except for Docker...

Can you see what is missing in my attempt to get Drupal up and running and served in a Docker container using your template?

Thanks very much for your help,
Stephen

**Comment by jlandfried** [comment]
Hey @smerth, thanks for checking this out and reporting this. It helped identify a few places where we can improve the documentation.

From the description it looks like you've done everything correctly. This should help with the two issues you mention:

-----

> However, when I go to http://localhost:8080 I get a "You don't have permission to access / on this server." with this kind of feedback from the console:

Whoops, we moved the docroot for Drupal to the `web` directory, which is something that Pantheon allows, but forgot to update the docs in the section about how you access the Drupal site. If you visit `http://localhost:8081/web` you should actually hit index.php

-------

> BTW, I can access a database named drupal at: mysql -h 127.0.0.1 --port 33306 but there are no tables in it, So I guess Docker is not actually installing Drupal?

Correct. We should add some documentation around this as well I suppose. Installing Drupal's not something that gets done right away when the containers are brought up. I typically handle it by shelling into the `drupal` container and using drupal console to do a fresh install from there if I need one.

From the project root:
```
docker-compose exec drupal /bin/bash
```

From within the container:
```
cd web;
../vendor/bin/drupal site:install

# ... install steps ...

../vendor/bin/drupal cr all
```

---------

Hope that helps!

**Comment by smerth** [comment]
Hi there @jlandfried,

Thanks for the quick response!!  I set in yesterday morning to try out your suggestions but had to do a bit of study on Docker first.  Have a couple of questions:

I have two sites installed using Docker and the scaffold. Yeah :-).  I edited the MySQL and Drupal config in the `docker-compose.yml` file so they each use their own db name, db user, and db password...

1. I can access one site at a time.  I use `docker-compose up` from the root of either project and I can get to that site... But I can't seem to get both sites up and running at the same time.  I tried changing the ports for one of the sites in the config so there wouldn't be any conflict but in the browser I get a message that says I can't reach the site because the server is busy...  Can Docker spin up two sites at the same time? Or is it designed only to serve one at a time?  Maybe there just isn't enough resource allocated in the LAMP config to support two sites at one time... Any clue about this would be appreciated.

2. With or without Varnish the site on Docker loads a lot slower than my localhost...  Is that normal?  Can I do anything about that?

3. I wrote some notes about getting running with the repo... you can see them here [NOTES](https://smerth.github.io/content/books/drupal-8-scaffold/book/index.html).  If you want I could add a doc folder and the md file to your repo and make a pull request... I haven't made a pull request to contribute to anyone else repo yet and I would happy to learn how...  (if its useful...)

4. How do you use Redis at LCM?  Is it used to store `key: value` pairs from Drupal 8 config files??

Well, thats probably 4 questions too many... thanks a lot for your help.  Next I will get into how to manage the coding and theme development with your Gulp build and use git to keep the whole process rolling.

**Comment by jlandfried** [comment]
Hey @smerth 
Cool, sounds like you made some progress.

-------

> I can access one site at a time. I use docker-compose up from the root of either project and I can get to that site... But I can't seem to get both sites up and running at the same time. I tried changing the ports for one of the sites in the config so there wouldn't be any conflict but in the browser I get a message that says I can't reach the site because the server is busy... Can Docker spin up two sites at the same time? Or is it designed only to serve one at a time? Maybe there just isn't enough resource allocated in the LAMP config to support two sites at one time... Any clue about this would be appreciated.

With some config I don't think there's any reason you couldn't have two sites running at the same time, but it's not a use case we typically handle with this. I just gave it a try and the one thing that I had to do was with the second site I brought up removed the ports for the varnish container in `docker-compose.yml`, and made sure that they were defined to something other than `8080:80` in `docker-compose.debug.yml`, since trying to have both sites serving varnish on `8080` causes a conflict.

Also, just so its clear, I ran `docker-compose up` twice, one from the root of each site that was being served. Typically imo it's easier to just bring up the site I'm currently working on, that way I'm not trying to keep track of different ports for different sites, but it is possible.

--------

> With or without Varnish the site on Docker loads a lot slower than my localhost... Is that normal? Can I do anything about that?

Am I right in guessing that you're on a mac? If so, there are some [known performance issues with OSXFS](https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/177). Some people are using tools like [docker-sync](http://docker-sync.io/) to help with that, YMMV. It's not something that we use so I can't really talk too much on the configuration of it or the performance gains it provides.

---------

> I wrote some notes about getting running with the repo... you can see them here NOTES. If you want I could add a doc folder and the md file to your repo and make a pull request... I haven't made a pull request to contribute to anyone else repo yet and I would happy to learn how... (if its useful...)

Sounds cool, though I'm not able to see those docs because the link points to localhost 😜 . I'd love to take a look at the notes though, and maybe we could put an issue together for adding some notes or updating the readme a bit.

-----------

> How do you use Redis at LCM? Is it used to store key: value pairs from Drupal 8 config files??

We typically use it for the default cache backend, then use the chainedfast backend for more frequently used items. You can see the config here: https://github.com/LastCallMedia/Drupal-Scaffold/blob/master/web/sites/default/settings.docker.php#L23. You'll need to enable the redis module to use it, so the config is commented out by default.

---------

> Well, thats probably 4 questions too many... thanks a lot for your help. Next I will get into how to manage the coding and theme development with your Gulp build and use git to keep the whole process rolling.

Np! Sounds good, feel free to ask about any other questions that come up.

**Comment by smerth** [comment]
Thanks! 

That clears up a lot of issues for me.  I am really excited to work in this new way with Drupal since it fits the structure of my non-Drupal projects and makes managing a Drupal code-base on Github much lighter!

Here's the link to the notes: [NOTES](https://smerth.github.io/content/books/drupal-8-scaffold/book/index.html)

I am going to add to them and edit them as I learn about using composer to manage module updates etc... 

Thanks again.

**Comment by jlandfried** [comment]
@smerth just wanted to follow up and say those notes are looking awesome. We'd definitely be interested in getting some more detailed docs in place. We haven't really decided on a format yet, maybe something like a github wiki, but I'm sure we'll be looking for any help people have to offer there as well :-)

Good luck with the next steps (composer, etc)! Definitely feel free to drop another note if you have any questions about that stuff.
