### ISSUE TITLE
Add Quicksilver hooks for automated deployments

### ISSUE THREAD

**Issue by rbayliss** [LastCallMedia/Drupal-Scaffold#34]
Can't believe we don't have a pantheon.yml in this repository.  Anyway, let's add some Quicksilver hooks to handle updb, and optionally, config import on deployments.  I think it'd be great to just have a single script (deploy_code.php) that handles both, and gets called anytime you'd want those things to happen (clone_database, sync_code, deploy).  This is a best practice, and helps ensure the deployment process is consistent.

**Comment by smerth** [comment]
Currently how would I go about deploying to Pantheon?

**Comment by jlandfried** [comment]
Hey @smerth, good question.

This project comes mostly pre-configured to deploy to Pantheon from CircleCI, which is the CI service that they're favoring as well in most of their examples and documentation. We should definitely add these notes in the readme as well, but to deploy to Pantheon from Circle, two things need to happen (assuming you've got the site set up on Pantheon already, and the project is in CircleCI):

- Update two environment variables in `circle.yml`
  - `PSITE`: The uuid of the pantheon site you're attempting to push to.
    - I've always just gotten this from the url of the site while looking at the dashboard. It should be something like `https://dashboard.pantheon.io/sites/{UUID-APPEARS-HERE}#dev/code`
  - `DOWNSTREAM`: The git url that you get from the Pantheon dashboard
- Set an environment variable in the circle dashboard for `PMACHINE`
  - This is a [terminus machine token](https://dashboard.pantheon.io/account#account/tokens) that will allow the scripts in `circle.yml` to run as a user authenticated with Pantheon
  - Technically this could be added to `circle.yml`, but as it's private info we put it in the dashboard so it's not in VCS.

After that, the `circle.yml` is configured to push an artifacts for branches that meet one of two conditions:

- The commit was pushed to `master`
  - Will deploy to the Pantheon `dev` envioronment, in the production pipeline
- The branch name starts with `p-` (ex: `p-homepage`)
  - will deploy to a multidev environment with the same name as the branch. If the multidev environment doesn't exist, it will attempt to create it.
  - We chose this pattern so it was still easy to make feature branches that _wouldn't_ get deployed to pantheon if we wanted to

-----------

### Without CircleCI

If deploying from CircleCI isn't something that you'd like to do, you can check out the `deployment` section of circle.yml to see the steps that the CI service is taking. Nothing in there is really CircleCI specific (with the exception of maybe using some environment variables that it provides for things like commit messages, but those shouldn't be required). The `push-to-downstream.sh` script in the `ci` directory does a lot of the heavy lifting there.

**Comment by rbayliss** [comment]
Fixed in #64
