### ISSUE TITLE
Steps to deploy to Pantheon

### ISSUE THREAD

**Issue by abendy** [LastCallMedia/Drupal-Scaffold#76]
I have this running on my local just fine. I tried to push this to a Pantheon instance and I'm receving this error:

`Warning: require(/var/www/web/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/web/autoload.php on line 17

Fatal error: require(): Failed opening required '/var/www/web/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/web/autoload.php on line 17`

**Comment by abendy** [comment]
Solution: create custom upstream

**Comment by abendy** [comment]
I created a custom upstream with this repo but I still get the same error

**Comment by chrismshelton** [comment]
Hi @abendy,
Did you get this figured out? If not, I'm wondering how you're deploying to pantheon - are you going through CircleCI?
